const meals=[
  {type:'desayuno',name:'Porridge de cacao y tahini',kcal:420,img:'https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=700&q=80'},
  {type:'comida',name:'Bowl de tofu y edamame',kcal:610,img:'https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=700&q=80'},
  {type:'merienda',name:'Tostada de hummus',kcal:260,img:'https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=700&q=80'},
  {type:'cena',name:'Curry de garbanzos',kcal:540,img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=700&q=80'},
  {type:'extra',name:'Yogur vegetal + fruta',kcal:190,img:'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=700&q=80'}
];
const recipes=[
  {name:'Bowl de tofu crujiente',desc:'Tofu, arroz, edamame y verduras de temporada.',kcal:'610 kcal · 34 g proteína',tag:'alta proteína',img:'https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=800&q=80'},
  {name:'Porridge de cacao',desc:'Avena, plátano, tahini y semillas de cáñamo.',kcal:'420 kcal · 18 g proteína',tag:'desayuno',img:'https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=800&q=80'},
  {name:'Curry de garbanzos',desc:'Cremoso, especiado y listo en menos de 25 minutos.',kcal:'540 kcal · 24 g proteína',tag:'en 25 min',img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80'},
  {name:'Tostada de hummus',desc:'Pan integral, hummus, tomate y brotes verdes.',kcal:'260 kcal · 10 g proteína',tag:'rápida',img:'https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=800&q=80'},
  {name:'Ensalada de lentejas',desc:'Lentejas, pepino, hierbas frescas y vinagreta.',kcal:'390 kcal · 22 g proteína',tag:'vegana',img:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80'},
  {name:'Yogur vegetal',desc:'Yogur de soja, frutos rojos, nueces y canela.',kcal:'190 kcal · 12 g proteína',tag:'snack',img:'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80'}
];
const mealGrid=document.querySelector('#meal-grid');
mealGrid.innerHTML=meals.map(m=>`<article class="meal-card"><div class="meal-art" style="background-image:url('${m.img}')"></div><div class="meal-body"><small>${m.type}</small><strong>${m.name}</strong><span>${m.kcal} kcal</span></div></article>`).join('');
document.querySelector('#recipe-grid').innerHTML=recipes.map(r=>`<article class="recipe-card" data-tags="${r.tag==='alta proteína'?'protein ':''}${r.tag==='vegana'?'vegana ':''}${r.tag==='rápida'?'quick ':''}${r.tag==='desayuno'?'breakfast ':''}"><div class="recipe-photo" style="background-image:url('${r.img}')"></div><div class="recipe-info"><span class="tag">${r.tag}</span><h3>${r.name}</h3><p>${r.desc}</p><strong>${r.kcal}</strong></div></article>`).join('');
const days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
document.querySelector('#week-board').innerHTML=days.map((d,i)=>`<div class="week-row"><div class="day">${d}<small class="eyebrow"> · ${11+i} sep</small></div>${['Desayuno','Comida','Merienda','Cena','+ añadir'].map((m,j)=>`<div class="meal-cell">${i<2&&j<4?`<strong>${['Porridge','Bowl de tofu','Fruta + nueces','Curry'][j]}</strong><small>${[420,610,260,540][j]} kcal</small>`:`<span>${m}</span>`}</div>`).join('')}</div>`).join('');
document.querySelector('.main-content').insertAdjacentHTML('beforeend',`<section class="view" id="calculo"><div class="section-heading"><div><span class="eyebrow">tu estimación energética</span><h2>Mi cálculo metabólico</h2></div><span class="status-pill">editable</span></div><div class="calc-layout"><form class="calc-card" id="calc-form"><p class="calc-note">Rellena los datos y revisa cada cifra. Nutrition Lab utiliza la ecuación Mifflin–St Jeor para estimar el gasto en reposo y después aplica el nivel de actividad.</p><div class="calc-grid"><label>Edad<input name="age" type="number" min="18" required /></label><label>Peso (kg)<input name="weight" type="number" min="35" step="0.1" required /></label><label>Altura (cm)<input name="height" type="number" min="130" required /></label><label>Actividad<select name="activity"><option value="1.2">Baja</option><option value="1.375">Ligera</option><option value="1.55">Moderada</option><option value="1.725">Alta</option></select></label></div><button class="primary-btn" type="submit">Actualizar cálculo <span>→</span></button></form><div class="formula-card"><span class="eyebrow">ecuación visible</span><h3>Mifflin–St Jeor</h3><p>Hombres: (10 × peso) + (6,25 × altura) − (5 × edad) + 5</p><p>Mujeres: (10 × peso) + (6,25 × altura) − (5 × edad) − 161</p><div class="calc-results"><div><strong id="calc-bmr">—</strong><small>kcal en reposo</small></div><div><strong id="calc-target">—</strong><small>kcal estimadas al día</small></div></div></div></div></section>`);
const views=document.querySelectorAll('.view'), navItems=document.querySelectorAll('[data-view]');
function showView(id){views.forEach(v=>v.classList.toggle('active-view',v.id===id));navItems.forEach(n=>n.classList.toggle('active',n.dataset.view===id));document.querySelector('#page-title').innerHTML=id==='inicio'?'Buenos días, María <span>✳</span>':({semana:'Tu plan semanal',recetas:'Recetas para ti',progreso:'Tu progreso',calculo:'Mi cálculo metabólico'}[id]||'Nutrition Lab');window.scrollTo({top:0,behavior:'smooth'});}
navItems.forEach(n=>n.addEventListener('click',()=>{showView(n.dataset.view);document.querySelector('.sidebar').classList.remove('open')}));document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewLink)));
document.querySelector('.mobile-menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
const modal=document.querySelector('#modal');document.querySelector('#add-food-btn').addEventListener('click',()=>modal.classList.add('open'));document.querySelector('#modal-close').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.add==='photo')document.querySelector('#photo-input').click();else{modal.classList.remove('open');showToast(b.dataset.add==='recipe'?'Abriendo recetas para ti ✦':'Buscador de alimentos listo ✦')}}));document.querySelector('#photo-input').addEventListener('change',e=>{modal.classList.remove('open');if(e.target.files.length)showToast('Foto recibida: revisaremos la etiqueta ✦')});
document.querySelector('#generate-btn').addEventListener('click',()=>showToast('Semana sugerida con tus preferencias ✦'));
const saveWeekButton=document.createElement('button');saveWeekButton.className='outline-btn';saveWeekButton.id='save-week-btn';saveWeekButton.textContent='Guardar semana';document.querySelector('#semana .section-heading').append(saveWeekButton);
async function saveWeek(){const profile=JSON.parse(localStorage.getItem('nutritionLabProfile')||'null');if(!profile?.email){showToast('Completa tu perfil para guardar la semana');return}const plan={email:profile.email,days:days.map(day=>({day,meals:meals.map(meal=>({type:meal.type,name:meal.name,kcal:meal.kcal}))}))};localStorage.setItem('nutritionLabPlan',JSON.stringify(plan));if(location.protocol!=='file:'){try{await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(plan)})}catch{}}showToast('Semana guardada en tu espacio ✦')}
saveWeekButton.addEventListener('click',saveWeek);
function filterRecipes(){const active=document.querySelector('.filter.selected')?.dataset.filter||'all';const search=(document.querySelector('#recipe-search')?.value||'').toLowerCase();document.querySelectorAll('.recipe-card').forEach(card=>{const matchesFilter=active==='all'||card.dataset.tags.includes(active);const matchesSearch=!search||card.textContent.toLowerCase().includes(search);card.style.display=matchesFilter&&matchesSearch?'block':'none'})}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');filterRecipes()}));document.querySelector('#recipe-search').addEventListener('input',filterRecipes);
document.querySelectorAll('.habit-list label').forEach(l=>l.addEventListener('click',()=>setTimeout(()=>{const n=[...document.querySelectorAll('.habit-list input:checked')].length;document.querySelector('.progress-label').textContent=`${n} de 5`},0)));
function showToast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
const aiPanel=document.querySelector('#ai-panel'),aiBody=document.querySelector('#ai-body'),aiInput=document.querySelector('#ai-input');
document.querySelector('#ai-fab').addEventListener('click',()=>{aiPanel.classList.add('open');aiInput.focus()});document.querySelector('#ai-close').addEventListener('click',()=>aiPanel.classList.remove('open'));
document.querySelectorAll('.ai-suggestions button').forEach(b=>b.addEventListener('click',()=>sendAiMessage(b.textContent)));
document.querySelector('#ai-form').addEventListener('submit',e=>{e.preventDefault();const value=aiInput.value.trim();if(value)sendAiMessage(value)});
function sendAiMessage(text){const user=document.createElement('div');user.className='ai-message user';user.textContent=text;aiBody.appendChild(user);aiInput.value='';aiBody.scrollTop=aiBody.scrollHeight;setTimeout(()=>{const reply=document.createElement('div');reply.className='ai-message assistant';reply.textContent=aiReply(text);aiBody.appendChild(reply);aiBody.scrollTop=aiBody.scrollHeight},450)}
function aiReply(text){const q=text.toLowerCase();const profile=JSON.parse(localStorage.getItem('nutritionLabProfile')||'null');const diet=profile?.diet==='vegan'?'vegana ':'';if(q.includes('tofu'))return`Puedes probar un bowl ${diet}de tofu crujiente con edamame, arroz y verduras. Aporta proteína vegetal y se prepara en unos 20 minutos.`;if(q.includes('600')||q.includes('cena'))return`Para una cena cercana a 600 kcal: ${diet?'tofu':'una fuente de proteína'}, arroz cocido, verduras salteadas y una cucharadita de aceite. Ajusta la cantidad según tu hambre y el resto del día.`;if(q.includes('entrenar'))return'Después de entrenar puedes combinar proteína y carbohidratos: yogur de soja con fruta y avena, o un bowl de tofu con arroz.';return'Puedo ayudarte con recetas, planificación semanal, sustituciones y lectura de etiquetas. Para afinar la respuesta, dime tu objetivo y qué alimentos tienes disponibles.'}
const setupModal=document.querySelector('#setup-modal'),setupForm=document.querySelector('#setup-form');
function calculateProfile(data){const base=data.sex==='male'?(10*data.weight+6.25*data.height-5*data.age+5):(10*data.weight+6.25*data.height-5*data.age-161);let target=Math.round(base*Number(data.activity));if(data.goal==='lose')target-=250;if(data.goal==='gain')target+=200;return{...data,bmr:Math.round(base),target};}
function applyProfile(profile){document.querySelector('.profile-mini strong').textContent=profile.name;document.querySelector('.profile-mini small').textContent=profile.goal==='gain'?'Objetivo: ganar músculo':profile.goal==='lose'?'Objetivo: perder grasa':'Objetivo: '+profile.goal;document.querySelector('#page-title').innerHTML=`Buenos días, ${profile.name} <span>✳</span>`;document.querySelectorAll('.avatar').forEach(a=>a.textContent=profile.name.slice(0,1).toUpperCase());const target=profile.target||2300;document.querySelector('.energy-number').innerHTML=`${target.toLocaleString('es-ES')} <span>kcal</span>`;document.querySelector('.ai-welcome .eyebrow').textContent=`hola, ${profile.name}`;}
const storedProfile=localStorage.getItem('nutritionLabProfile');if(storedProfile){const profile=JSON.parse(storedProfile);applyProfile(profile);setupModal.classList.add('hidden')}
async function persistProfile(profile){localStorage.setItem('nutritionLabProfile',JSON.stringify(profile));if(location.protocol!=='file:'){try{const response=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});if(!response.ok)throw new Error('No se pudo guardar');return true}catch(error){showToast('Guardado local activado mientras conectamos el servidor');}}return false}
setupForm.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(setupForm);const data={name:f.get('name'),email:f.get('email'),age:Number(f.get('age')),sex:f.get('sex'),weight:Number(f.get('weight')),height:Number(f.get('height')),activity:f.get('activity'),goal:f.get('goal'),diet:f.get('diet'),meals:Number(f.get('meals'))};if(data.age<18){showToast('Nutrition Lab está disponible para mayores de 18 años');return}const profile=calculateProfile(data);await persistProfile(profile);applyProfile(profile);setupModal.classList.add('hidden');showToast('Tu espacio está listo ✦')});
const customModal=document.querySelector('#custom-modal'),customForm=document.querySelector('#custom-form');
document.querySelector('[data-add="custom"]').addEventListener('click',()=>{modal.classList.remove('open');customModal.classList.add('open')});document.querySelector('#custom-close').addEventListener('click',()=>customModal.classList.remove('open'));customModal.addEventListener('click',e=>{if(e.target===customModal)customModal.classList.remove('open')});
customForm.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(customForm),file=f.get('photo');const meal={type:f.get('type'),name:f.get('name'),kcal:Number(f.get('kcal')||0),protein:Number(f.get('protein')||0),notes:f.get('notes'),img:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=80'};if(file&&file.size){const reader=new FileReader();reader.onload=()=>{meal.img=reader.result;saveCustomMeal(meal)};reader.readAsDataURL(file)}else saveCustomMeal(meal)});
function saveCustomMeal(meal){const custom=JSON.parse(localStorage.getItem('nutritionLabCustomMeals')||'[]');custom.push(meal);localStorage.setItem('nutritionLabCustomMeals',JSON.stringify(custom));const card=document.createElement('article');card.className='meal-card';card.innerHTML=`<div class="meal-art" style="background-image:url('${meal.img}')"></div><div class="meal-body"><small>${meal.type}</small><strong>${meal.name}</strong><span>${meal.kcal} kcal</span></div>`;mealGrid.appendChild(card);customForm.reset();customModal.classList.remove('open');showToast('Tu comida se ha añadido libremente ✦')}
const dayModal=document.querySelector('#day-modal'),dayMeals=document.querySelector('#day-meals');document.querySelector('#day-close').addEventListener('click',()=>dayModal.classList.remove('open'));dayModal.addEventListener('click',e=>{if(e.target===dayModal)dayModal.classList.remove('open')});
document.querySelectorAll('.week-tabs button').forEach((button,index)=>button.addEventListener('click',()=>openDay(index,button.textContent)));
function openDay(index,label){const custom=JSON.parse(localStorage.getItem('nutritionLabCustomMeals')||'[]');const list=index===1?[...meals,...custom]:custom;document.querySelector('#day-title').textContent=label+' de septiembre';document.querySelector('#day-total').textContent=`${list.reduce((sum,m)=>sum+Number(m.kcal||0),0).toLocaleString('es-ES')} kcal registradas · ${list.length} comidas`;dayMeals.innerHTML=list.length?list.map(m=>`<div class="day-meal"><div class="day-meal-img" style="background-image:url('${m.img}')"></div><div><strong>${m.name}</strong><small>${m.type}${m.protein?` · ${m.protein} g proteína`:''}</small></div><b>${m.kcal} kcal</b></div>`).join(''):'<p class="calc-note">Todavía no hay comidas guardadas para este día.</p>';dayModal.classList.add('open')}
function fillCalculator(profile){const form=document.querySelector('#calc-form');if(!form||!profile)return;form.age.value=profile.age||'';form.weight.value=profile.weight||'';form.height.value=profile.height||'';form.activity.value=profile.activity||'1.55';updateCalculator(profile)}function updateCalculator(data){const calculated=calculateProfile({...data,age:Number(data.age),weight:Number(data.weight),height:Number(data.height),activity:data.activity||'1.55'});document.querySelector('#calc-bmr').textContent=calculated.bmr.toLocaleString('es-ES');document.querySelector('#calc-target').textContent=calculated.target.toLocaleString('es-ES')}const calcProfile=JSON.parse(localStorage.getItem('nutritionLabProfile')||'null');fillCalculator(calcProfile);document.querySelector('#calc-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),profile=JSON.parse(localStorage.getItem('nutritionLabProfile')||'{}');const next=calculateProfile({...profile,age:Number(f.get('age')),weight:Number(f.get('weight')),height:Number(f.get('height')),activity:f.get('activity')});localStorage.setItem('nutritionLabProfile',JSON.stringify(next));applyProfile(next);updateCalculator(next);showToast('Cálculo actualizado ✦')});
